name: Uno

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-maccatalyst-test:
    runs-on: macos-15
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: '10.0.x'

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Setup
        run:
          dotnet workload install ios
          dotnet workload install android

      - name: Run tests
        run:
          dotnet run --project samples/basic/AppTester -c Release --report-trx --no-progress --test-groups uno-maccatalyst

      - name: Publish results
        uses: dorny/test-reporter@v2.2.0
        with:
          name: test-results
          path: samples/basic/AppTester/bin/Release/net10.0/TestResults/*.trx
          reporter: dotnet-trx